# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  font: serif

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Threefold Social Order'
    description: 'Podcast dedicated to understanding Rudolf Steiner's concept of a non-binary Social structure based on three primary components with autonomy to administer their respective spheres'
    twitter: 'Threefold Social Order Podcast'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    show_search: true
    show_theme_chooser: true
    logo:
      text: ""

# Site footer
footer:
  copyright:
    notice: '© {year} Stephen Joy. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
